### ISSUE TITLE
[Evil Story Epic] Sécurisation des Transactions

### ISSUE THREAD

**Issue by QuenumGerald** [QuenumGerald/Wall-ee#14]
Prévenir les attaques de type Man-in-the-Middle (MitM) et autres formes d'interception de transactions.

Tâches à réaliser :
- [ ] Utiliser des protocoles de communication sécurisés.
- [ ] Mettre en œuvre des mécanismes de validation et de confirmation des transactions.
- [ ] Éduquer les utilisateurs sur les bonnes pratiques de sécurité.
