### ISSUE TITLE
[Evil Story Epic] Protection contre le Vol de Fonds

### ISSUE THREAD

**Issue by QuenumGerald** [QuenumGerald/Wall-ee#15]
Mettre en place des stratégies pour prévenir le vol de crypto-monnaies du wallet.

Tâches à réaliser :
- [ ] Implémenter des limites de transaction et des alertes pour les activités suspectes.
- [ ] Offrir des options de sécurité supplémentaires comme l'authentification à deux facteurs (2FA).
- [ ] Réaliser des audits de conformité et de sécurité réguliers.
