### ISSUE TITLE
[Epic] Fonctionnalités de Transaction de Crypto-monnaies

### ISSUE THREAD

**Issue by QuenumGerald** [QuenumGerald/Wall-ee#3]
Intégrer les fonctionnalités de transaction dans le wallet blockchain pour permettre aux utilisateurs d'envoyer et de recevoir des crypto-monnaies.
Implémentation de :
- Envoi de crypto-monnaies
- Réception de crypto-monnaies
- Interface utilisateur pour les transactions

Tâches à faire :
- [ ] Envoi de crypto-monnaies
- [ ] Réception de crypto-monnaies
- [ ] Interface utilisateur pour les transactions
